### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by hitdwb** [wonderivan/logger#1]
（1）Dial如果网络超时，DialTimeout
（2）选项，输出日志是否到终端，如果日志文件可以选择不输出到终端
（3）分日志文件打印，一般Notice为了日志统计使用的，选择日志级别，打印到某个文件，其他的打印到一个文件。

**Comment by aryming** [comment]
好，我找时间完善一下

**Comment by wonderivan** [comment]
调研过后，这类需求不是很大，可以通过filebeat采集生成的file文件，或者 conn方式直接上报到Logstash，然后通过ES进行分类解析，本地日志分析，可以直接通过grep，或者grep+重定向进行日志分析

**Comment by aryming** [comment]
调研过后，这类需求不是很大，可以通过filebeat采集生成的file文件，或者 conn方式直接上报到Logstash，然后通过ES进行分类解析，本地日志分析，可以直接通过grep，或者grep+重定向进行日志分析
