### ISSUE TITLE
readme中日志输出级别的问题

### ISSUE THREAD

**Issue by mornone** [wonderivan/logger#2]
文档中“当前日志输出等级共8种，从0-7对应的等级由高到底，当配置为某个输出等级时，只有大于等于该等级的日志才会输出。”
实际使用中发现当小于等于设置的等级日志才会输出到file中，不知道是否是使用方法有误。
刚进入go，谢谢造的轮子

**Comment by aryming** [comment]
可能是你使用有误吧，go test有相关用例，可以用于验证
